const CurrencyMetadata = {
  CAD: { label: 'Canadian dollar', flag: require('../images/CAD.png') },
  AUD: { label: 'Australian dollar', flag: require('../images/AUD.png') },
  BRL: { label: 'Brazilian real', flag: require('../images/BRL.png') },
  CNY: { label: 'Chinese renminbi', flag: require('../images/CNY.png') },
  EUR: { label: 'European euro', flag: require('../images/EUR.png') },
  HKD: { label: 'Hong Kong dollar', flag: require('../images/HKD.png') },
  INR: { label: 'Indian rupee', flag: require('../images/INR.png') },
  IDR: { label: 'Indonesian rupiah', flag: require('../images/IDR.png') },
  JPY: { label: 'Japanese yen', flag: require('../images/JPY.png') },
  MYR: { label: 'Malaysian ringgit', flag: require('../images/MYR.png') },
  MXN: { label: 'Mexican peso', flag: require('../images/MXN.png') },
  NZD: { label: 'New Zealand dollar', flag: require('../images/NZD.png') },
  NOK: { label: 'Norwegian krone', flag: require('../images/NOK.png') },
  PEN: { label: 'Peruvian new sol', flag: require('../images/PEN.png') },
  RUB: { label: 'Russian ruble', flag: require('../images/RUB.png') },
  SAR: { label: 'Saudi riyal', flag: require('../images/RUB.png') },
  SGD: { label: 'Singapore dollar', flag: require('../images/SGD.png') },
  ZAR: { label: 'South African rand', flag: require('../images/ZAR.png') },
  KRW: { label: 'South Korean won', flag: require('../images/KRW.png') },
  SEK: { label: 'Swedish krona', flag: require('../images/SEK.png') },
  CHF: { label: 'Swiss franc', flag: require('../images/CHF.png') },
  TWB: { label: 'Taiwanese dollar', flag: require('../images/THB.png') },
  THB: { label: 'Thai baht', flag: require('../images/THB.png') },
  GBP: { label: 'UK pound sterling', flag: require('../images/GBP.png') },
  USD: { label: 'US dollar', flag: require('../images/USD.png') },
  VND: { label: 'Vietnamese dong', flag: require('../images/VND.png') }
};

export default CurrencyMetadata;
